@id = 3710d38c-1e7d-4de2-82b8-8671ba73b7ae
PUT http://localhost:5241/CreateItem/{{id}}
Content-Type: application/json

{
    "name": "Laptop",
    "discription": "A portable Computor",
    "price": "1500",
    "dayAdded": "2022-04-08T11:00:00"
}