@id = 2b6752de-3787-4268-81cb-4d47541a7a41
PUT http://localhost:5241/CreateItem/{{id}}
Content-Type: application/json

{
    "name": "Laptop",
    "discription": "A portable Computer",
    "price": "1600",
    "dayAdded": "2022-04-08T11:00:00"
}